In [1]:
import pandas as pd

In [2]:
production_df = pd.read_csv('./data/05_production.csv', encoding='utf-8-sig')
quality_df = pd.read_csv('./data/07_quality_inspection.csv', encoding='utf-8-sig', na_values=['\\N'])
sensor_df = pd.read_csv('./data/08_sensor_data.csv', encoding='utf-8-sig')
operation_df = pd.read_csv('./data/06_equipment_operation.csv', encoding='utf-8-sig')
equipment_df = pd.read_csv('./data/01_equipment.csv', encoding='utf-8-sig')

# 날짜/시간 변환
production_df['production_date'] = pd.to_datetime(production_df['production_date'])
production_df['start_time'] = pd.to_datetime(production_df['start_time'])
production_df['end_time'] = pd.to_datetime(production_df['end_time'])
sensor_df['measurement_time'] = pd.to_datetime(sensor_df['measurement_time'])
operation_df['start_time'] = pd.to_datetime(operation_df['start_time'])
operation_df['end_time'] = pd.to_datetime(operation_df['end_time'])

In [3]:
sensor_df['measurement_time'].unique()

<DatetimeArray>
['2024-01-01 00:00:00', '2024-01-01 01:00:00', '2024-01-01 02:00:00',
 '2024-01-01 03:00:00', '2024-01-01 04:00:00', '2024-01-01 05:00:00',
 '2024-01-01 06:00:00', '2024-01-01 07:00:00', '2024-01-01 08:00:00',
 '2024-01-01 09:00:00',
 ...
 '2024-03-31 14:00:00', '2024-03-31 15:00:00', '2024-03-31 16:00:00',
 '2024-03-31 17:00:00', '2024-03-31 18:00:00', '2024-03-31 19:00:00',
 '2024-03-31 20:00:00', '2024-03-31 21:00:00', '2024-03-31 22:00:00',
 '2024-03-31 23:00:00']
Length: 2184, dtype: datetime64[ns]

In [4]:
sensor_df.head(2)

,sensor_id,equipment_id,measurement_time,temperature,pressure,vibration,current,voltage,rpm,created_at
0,1,INJ-001,2024-01-01,183.93,148.65,2.6838,48.05,218.83,1795.32,2026-01-30 00:45:52
1,2,INJ-002,2024-01-01,173.06,144.23,2.2576,39.17,211.38,1738.75,2026-01-30 00:45:52

In [5]:
sensor_1=sensor_df[sensor_df['equipment_id'] == 'INJ-001'] \
    .sort_values(by='measurement_time')

In [6]:
sensor_1.reset_index(drop=True, inplace=True)

In [7]:
#resample 함수를 이용해서 datetime을 조절할 때는 
# datetime컬럼이 무조건 인덱스로 되어 있어야 한다.
sensor_1.set_index('measurement_time')[['temperature','pressure','vibration','current','voltage','rpm']].resample('D').mean()

,temperature,pressure,vibration,current,voltage,rpm
measurement_time,,,,,,
2024-01-01,180.656250,149.338750,2.499879,44.680417,221.020000,1801.248333
2024-01-02,179.808333,149.557083,2.453850,44.813333,221.112917,1803.249167
2024-01-03,180.512083,151.159583,2.553117,45.706250,220.699583,1800.577500
2024-01-04,181.021667,149.677083,2.460775,44.397083,218.150417,1800.027917
2024-01-05,180.211667,150.191667,2.487862,45.253750,219.357917,1799.818333
...,...,...,...,...,...,...
2024-03-27,193.929583,150.450833,2.500167,45.898333,220.992917,1799.215833
2024-03-28,193.542083,150.111667,2.467542,45.199583,220.824167,1804.017917
2024-03-29,194.460417,150.050000,2.516758,44.872083,220.793333,1799.270000
2024-03-30,194.767500,150.385417,2.466196,44.922083,219.166250,1805.192917
2024-03-31,195.773750,149.632917,2.494958,45.071667,219.956667,1803.921667

In [8]:
sensor_df

,sensor_id,equipment_id,measurement_time,temperature,pressure,vibration,current,voltage,rpm,created_at
0,1,INJ-001,2024-01-01 00:00:00,183.93,148.65,2.6838,48.05,218.83,1795.32,2026-01-30 00:45:52
1,2,INJ-002,2024-01-01 00:00:00,173.06,144.23,2.2576,39.17,211.38,1738.75,2026-01-30 00:45:52
2,3,PRESS-001,2024-01-01 00:00:00,82.29,202.09,3.4924,120.14,372.88,489.11,2026-01-30 00:45:52
3,4,PRESS-002,2024-01-01 00:00:00,87.62,194.68,3.7005,121.70,379.93,498.85,2026-01-30 00:45:52
4,5,ASM-001,2024-01-01 00:00:00,20.78,-0.94,1.1674,16.48,220.86,97.69,2026-01-30 00:45:52
...,...,...,...,...,...,...,...,...,...,...
10915,10916,INJ-001,2024-03-31 23:00:00,192.48,148.93,2.4576,48.58,226.34,1775.78,2026-01-30 00:45:52
10916,10917,INJ-002,2024-03-31 23:00:00,175.82,141.36,2.4609,44.68,226.68,1762.20,2026-01-30 00:45:52
10917,10918,PRESS-001,2024-03-31 23:00:00,84.57,191.96,3.5106,116.58,383.60,492.28,2026-01-30 00:45:52
10918,10919,PRESS-002,2024-03-31 23:00:00,87.53,202.47,3.8016,118.02,390.56,506.57,2026-01-30 00:45:52
10919,10920,ASM-001,2024-03-31 23:00:00,29.81,1.72,1.3399,14.58,225.46,97.61,2026-01-30 00:45:52

In [9]:
sensor_all =sensor_df.groupby('measurement_time')[['temperature',
                                           'pressure', 	'vibration',	'current',	'voltage',	'rpm']].mean()

In [10]:
sensor_all.resample('D').mean()

,temperature,pressure,vibration,current,voltage,rpm
measurement_time,,,,,,
2024-01-01,110.660667,139.611750,2.814983,68.186667,284.601583,932.055000
2024-01-02,111.031417,139.831500,2.686983,68.438750,284.228583,936.736667
2024-01-03,110.668000,140.153833,2.695356,68.191667,284.183250,932.576417
2024-01-04,110.718333,139.901167,2.712816,68.124250,284.065250,934.209417
2024-01-05,110.373833,139.653000,2.751715,68.151167,283.345417,934.190083
...,...,...,...,...,...,...
2024-03-27,113.264417,139.593083,2.667431,68.441833,285.089500,933.713583
2024-03-28,113.161583,139.867250,2.704023,68.069917,284.704333,935.672583
2024-03-29,113.754250,139.826000,2.767098,68.518333,284.464333,932.220750
2024-03-30,113.656000,139.506833,2.652366,68.054333,283.708167,935.188167
2024-03-31,113.881167,139.530833,2.710602,68.180917,284.325167,934.268500

In [11]:
## 이동편균 : 센서 데이터에는 노이즈가 많아서 추세 파악이 힘들다.
# 노이즈제거나 이상패턴 감지가 쉽다

In [12]:
# 진동센서 7일 이동평균이 상승 ->  베어링 교체, 
# 온도 30일 간 이동편균이 상승 -> 냉각 시스템 점검
# 측정값 이동평균 상한선 접근 -> 사전 경고를 해줄 수 있다.
# 생산량 이동평균으로 수요 예측 가능
# 계절성 패턴 파악 가능

In [13]:
sensor_1_day =sensor_1.set_index('measurement_time').resample('D')['temperature'].mean()

In [14]:
sensor_1_day.rolling(window=5).mean() #window는 몇개 간의 데이터는?

measurement_time
2024-01-01           NaN
2024-01-02           NaN
2024-01-03           NaN
2024-01-04           NaN
2024-01-05    180.442000
                 ...
2024-03-27    193.909250
2024-03-28    193.954500
2024-03-29    194.171917
2024-03-30    194.160583
2024-03-31    194.494667
Freq: D, Name: temperature, Length: 91, dtype: float64

In [15]:
# shift(1): 시계열 데이터에서 전날 또는 전 에 있던 데이터를 현재에 데이터에 옮길 수 있다. (x - x.shift(1))<- 이런식으로 계산 할 수 있다.

In [16]:
# diff 함수 : shift랑 비슷하지만 이거는 바로 증감을 알 수 있는 데이터다
# 전일 대비 증감 양을 보여주는 함수이다 ex> daily_production.diff

In [17]:
# pct_change() : 변화율 계산하는 법 ex> daily_production.pct_change()*100 <-- 이렇게 해야 퍼센티지로 나옴

In [18]:
#이상치 탐지

In [19]:
# IQR
# Z-score
# 3-sigma

In [20]:
#OEE (Overall Equipment Effectiveness)

In [21]:
# 가동률*성능률*양품률

In [22]:
# 가동률 = 실제 가동시간/ 계획 가동시간
# 성능률 = ( 실제 생산량 * 이상 사이클 타임) /실제 가동시간
# 양품률 = 양품수량/ 총생산량

In [23]:
# OEE 구해서 50% 미만 -> 현재의 설비 효율 개선하자.
# 85 이상 -> 설비 증설 검토

In [24]:
### 가동률이 낮다 -> 고장/ 정지시간을 줄이기 위한 방법을 찾아야 한다.
### 성능률이 낮다 -> 속도 개선, 교체 시간 단축 위한 방법을 찾아야 한다.
### 양품률이 낮다 -> 품질 개선, 재작업 감소하는 방법을 찾아야 한다.

In [25]:
### 벤치마킹 가능한다 -> 설비간 비교를 통해서, 우수 설비를 찾아낸다.

In [26]:
### 공장 간 비교가 가능하다. 우수공장은 Best paractice가 된다.

In [27]:
#OEE 계산 결과
# 85% 이상: 월클 수준
# 70~84% : 양호
# 60~69% : 보통 -> 개선 과제 도출
# 60% 미만 : 개선필요, 긴급 조치

In [28]:
production_df.head(2)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [29]:
production_df['불량률']=production_df['defect_quantity']/production_df['actual_quantity']*100

In [30]:
production_df.head(2)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at,불량률
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48,4.938272
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48,7.692308

In [ ]:
production_df[['target_quantity','actual_quantity','cycle_time','불량률']]

      target_quantity  actual_quantity  cycle_time        불량률
0                  97               81       73.73   4.938272
1                  83               78       70.56   7.692308
2                 149              135       81.99   2.222222
3                 100               92       96.87   2.173913
4                 123              129       67.08   5.426357
...               ...              ...         ...        ...
1867              150              144       77.63  17.361111
1868              136              130       76.15  16.153846
1869               84               80       69.95  17.500000
1870              143              121       90.10  16.528926
1871              106               90       81.80  17.777778

[1872 rows x 4 columns]

In [ ]:
# 상관 계수 분석 -1로 갈 수록 반 비례관계, 1로 갈 수록 비례

In [32]:
production_df[['target_quantity','actual_quantity','cycle_time','불량률']].corr()

                 target_quantity  actual_quantity  cycle_time       불량률
target_quantity         1.000000         0.930913    0.016590 -0.075707
actual_quantity         0.930913         1.000000   -0.085386 -0.117936
cycle_time              0.016590        -0.085386    1.000000  0.058185
불량률                    -0.075707        -0.117936    0.058185  1.000000